version: '3.5'

services:
    mongo:
            container_name: mongo
            image: mongo
            volumes:
            - ./data:/data/db
            ports:
            - "27018:27017"
    vernemq:
            environment:
                - DOCKER_VERNEMQ_ACCEPT_EULA=yes
                - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
                - MQTT_TOPIC=thndr-trading
            image: erlio/docker-vernemq
            volumes:
                - ~/docker/docker-vernemq/data:/data
            ports: 
                - "1883:1883"
                - "8888:8888"
    streamer:
            environment:
                - MQTT_HOST=vernemq
                - MQTT_PORT=1883
                - MQTT_TOPIC=thndr-trading
            image: thndr/streamer:0.2
            depends_on:
                - vernemq




